export { default as AccountSvg } from './account.svg';
export { default as CaloriesSvg } from './calories.svg';
export { default as FinancesSvg } from './finances.svg';
export { default as FridgeSvg } from './fridge.svg';
export { default as RecipesSvg } from './recipes.svg';
export { default as PlusSvg } from './plus.svg';
export { default as DefaultUserImage } from './defaultUserImage.svg';
export { default as SearchSvg } from './search.svg';
export { default as DeleteSvg } from './delete.svg';
